### ISSUE TITLE
Any suggestions for running this game on MacOS platform?

### ISSUE THREAD

**Issue by peterljq** [lrtray/AOTU-Reasoning-Game#1]
As what the title asked, this is indeed quite an interesting game, any suggestions for running it on MacOS? By the way, 在GitHub上发现凹凸粉实属难得🤝。

**Comment by KilluaSakata** [comment]
I feel so sorry about to reply for a reallly long time.
For MacOS,try to use virtual machines which is running on Windows 7 or later.
Of course,the MacOS edition is developing....
By the way...【这样真的好吗你居然还想炒冷饭啊雷翎同学x

That's all.Thanks for ur issue.

Lrtray/Link
19.8.1
